version: 2.1

orbs:
  node: circleci/node@4.0.0

defaults: &defaults
  docker:
    - image: cimg/base:stable-20.04
  working_directory: ~/repo

commands:
  install_cci_cli:
    description: Install the latest CircleCI CLI
    steps:
      - run:
          name: Install CCI CLI
          command: |
            sudo curl -fLSs https://circle.ci/cli | sudo bash
            # this succesfully installs the new cci CLI to /usr/local/bin/circleci
            # however, the orig (/usr/bin/circleci) remains in the path
            # so need to use the full path to circleci

            which /usr/local/bin/circleci
            /usr/local/bin/circleci version
            /usr/local/bin/circleci

jobs:

  # This renders all the relavent Orb files into a single file - packed/orb.yml
  pack-orb:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: See files after checkout
          command: |
            ls -la
      - install_cci_cli
      - run:
          name: Pack the Orb
          command: |
            mkdir packed
            /usr/local/bin/circleci orb pack src >> packed/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: packed/orb.yml

  # This deploys a dev version
  dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - install_cci_cli
      - run:
          name: Deploy dev version of Orb
          command: |
            dev_orb_ref="ffluk3/snyk@dev:${CIRCLE_BRANCH}"
            echo "dev_orb_ref: ${dev_orb_ref}"
            /usr/local/bin/circleci orb publish packed/orb.yml $dev_orb_ref --token ${CIRCLECI_TOKEN}

workflows:
  btd:
    jobs:
      - pack-orb
      - dev:
          context:
            - orb-publish
          requires:
            - pack-orb
